accounts/api/urls.py
from tweets.api.views import TweetListAPIView

from django.urls import path
app_name = 'api'
urlpatterns = [
    path('<slug:user_slug>/tweets/',
         TweetListAPIView.as_view(),
         name='profile_tweets'),

]

accounts/urls.py
from django.urls import path


from .views import (UserLoginView, UserRegistrerView, UserProfileUpdateView,
                    UserLogoutView, UserProfileView, UserFollow, ThemeChange,
                    FollowManager, FollowingView, FollowersView)
from tweets.api.views import ProfileLikeToggleApiView


app_name = 'accounts'
urlpatterns = [

    path('theme/', ThemeChange.as_view(), name='theme'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrerView.as_view(), name='register'),
    path('<slug:user_slug>/follow/', UserFollow.as_view(), name='follow'),
    path('<slug:user_slug>/follow_manage/',
         FollowManager.as_view(), name='follow_manage'),
    path('<slug:user_slug>/', UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('<slug:user_slug>/followers/',
         FollowersView.as_view(), name='followers'),
    path('<slug:user_slug>/following/',
         FollowingView.as_view(), name='following'),
    path('<slug:slug>/api/tweets/<int:pk>/like/',
         ProfileLikeToggleApiView.as_view(), name='user-like'),
]

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import (TweetListView,
                    TweetDetailView,
                    TweetCreateView,
                    TweetEditView,
                    TweetDeleteView,
                    RetweetView)

app_name = 'tweets'
urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),
    path('edit/<int:pk>/', TweetEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', TweetDeleteView.as_view(), name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.urls import reverse
from django_countries.fields import CountryField


from random import shuffle

from .utils import get_proimage_name, get_procover_name


class UserManager(BaseUserManager):

    def create_user(self, email, username, password=None,
                    is_active=True, is_staff=False, is_admin=False, subscribed=True):
        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.is_active = is_active
        user.is_staff = is_staff
        user.is_admin = is_admin
        user.subscribed = subscribed
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, username, password=None, subscribed=True):
        user = self.create_user(
            email, username, password=password, is_staff=True, subscribed=subscribed)
        return user

    def create_superuser(self, email, username, password=None, subscribed=True):
        user = self.create_user(email, username, password=password,
                                is_staff=True, is_admin=True, subscribed=subscribed)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address',
                              max_length=255, unique=True)
    username = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.username

    def get_shortname(self):
        return self.username

    def get_fullname(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_lable):
        return True

    def get_profile(self):
        try:
            profile = self.profile
        except:
            profile = None
        return profile

    def get_absolute_url(self):
        # return reverse('accounts:profile',kwargs={'user_slug':self.slug})
        return reverse('home')


class UserProfileManager(models.Manager):
    use_for_related_fields = True

    def all(self):
        qs = self.get_queryset().all()
        try:
            user = self.instance
            qs = qs.exclude(user=user)
        except:
            pass
        return qs

    def toggle_follow(self, user, toggle_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)

        if toggle_user in user_profile.following.all():
            user_profile.following.remove(toggle_user)
            added = False
        else:
            user_profile.following.add(toggle_user)
            added = True
        return added

    def is_following(self, user, followed_by_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if created:
            return False
        if followed_by_user in user_profile.following.all():
            return True
        return False

    def recommended(self, user, limit=5):
        profile = user.get_profile()
        following = profile.get_following()
        qs = self.get_queryset().exclude(user=user).exclude(user__in=following)
        return qs.order_by('?')[:limit]


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    following = models.ManyToManyField(
        User, related_name='followed_by', blank=True)
    avatar = models.ImageField(
        blank=True, null=True, upload_to=get_proimage_name)
    cover = models.ImageField(blank=True, null=True,
                              upload_to=get_procover_name)
    country = CountryField(blank=True, null=True)
    description = models.TextField(null=True, blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    birthday = models.DateField(blank=True, null=True)
    objects = UserProfileManager()
    color = models.CharField(max_length=120, default='#FF0000')

    def __str__(self):
        return self.user.username + ' profile'

    def get_absolute_url(self):
        return reverse('accounts:profile', kwargs={'user_slug': self.user.slug})

    def get_following(self):
        users = self.following.all()
        return users.exclude(username=self.user.username)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm
from .models import User, UserProfile

import re


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Email ", widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=("Password "),
        strip=False,
        widget=forms.PasswordInput,
    )
    remember_me = forms.BooleanField(required=False, label='Remember me')


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_password2(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]


class UserProfileForm(forms.ModelForm):
    birthday = forms.DateField(required=False, input_formats=['%Y-%m-%d'])

    class Meta:
        model = UserProfile
        exclude = ['user', 'following', 'color']

    def clean_birthday(self):
        birthday = self.cleaned_data.get('birthday')
        return birthday


class UserProfileColorForm(forms.ModelForm):
    color = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = UserProfile
        fields = ['color']

    def clean_color(self):
        regex = r'^\s*#[\w\d]{6}\s*$'
        color = self.cleaned_data.get('color')
        m = re.match(regex, color)
        if not m:
            raise forms.ValidationError('Please type a valid color code ')
        return m.string

accounts/views.py
from django.views.generic import DetailView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView)
from django.views import View
from django.views.generic import (ListView, CreateView, DetailView, UpdateView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseForbidden

from .forms import (LoginForm, RegistrationForm,
                    UserProfileForm, UserProfileColorForm)
from .models import UserProfile
from .mixins import AnonymousRequiredMixin


User = get_user_model()


class UserLoginView(AnonymousRequiredMixin, LoginView):
    authentication_form = LoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me', None)
        login(self.request, form.get_user())
        if remember_me:
            self.request.session.set_expiry(1209600)
        return super().form_valid(form)


class UserLogoutView(LogoutView):
    next_page = 'accounts:login'


class UserProfileView(DetailView):
    queryset = User.objects.all()
    template_name = 'accounts/profile.html'
    slug_url_kwarg = 'user_slug'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        user = self.request.user
        context['me'] = False

        if user.is_authenticated:
            if user.slug == context['object'].slug:
                context['me'] = True
            context['is_followed'] = UserProfile.objects.is_following(
                self.request.user, self.get_object())
        return context


class UserRegistrerView(AnonymousRequiredMixin, CreateView):
    form_class = RegistrationForm
    template_name = 'accounts/register.html'
    success_url = '/'


class UserFollow(LoginRequiredMixin, View):
    login_url = reverse_lazy('accounts:login')

    def get(self, request, user_slug, *args, **kwargs):
        user_following = get_object_or_404(User, slug=user_slug)

        if request.user.is_authenticated:
            follow_user = UserProfile.objects.toggle_follow(
                request.user, user_following)
            if request.is_ajax():
                user_status = 'Follow'
                if follow_user:
                    user_status = 'Unfollow'
                user_followers_num = user_following.followed_by.count()
                data = {'usrst': user_status,
                        'ufn': user_followers_num}
                return JsonResponse(data)
        return redirect('accounts:profile', user_slug=user_slug)


class FollowManager(LoginRequiredMixin, View):
    login_url = reverse_lazy('accounts:login')

    def get(self, request, user_slug, *args, **kwargs):
        user_following = get_object_or_404(User, slug=user_slug)
        if request.user.is_authenticated:
            follow_user = UserProfile.objects.toggle_follow(
                request.user, user_following)
            if request.is_ajax():
                user_status = 'Follow'
                if follow_user:
                    user_status = 'Unfollow'
                data = {'usrst': user_status}
                return JsonResponse(data)
        return redirect('accounts:following', user_slug=request.user.slug)


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    queryset = UserProfile.objects.all()
    form_class = UserProfileForm
    template_name = 'accounts/profile_edit.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=None)
        profile = self.request.user.profile
        if obj != profile:
            raise Http404
        return obj


class FollowersView(DetailView):
    queryset = User.objects.all()
    template_name = 'accounts/followers.html'
    slug_url_kwarg = 'user_slug'
    context_object_name = 'obj'


class FollowingView(DetailView):
    queryset = User.objects.all()
    template_name = 'accounts/following.html'
    slug_url_kwarg = 'user_slug'
    context_object_name = 'obj'


class ThemeChange(LoginRequiredMixin, View):
    login_url = '/account/login/'

    def get(self, request):
        return redirect('/')

    def post(self, request):
        path = request.POST.get('current_path')
        if not path:
            path = '/'
        form = UserProfileColorForm(
            request.POST or None, instance=request.user.profile)
        if form.is_valid():
            form.save()
        return redirect(path)

templates/accounts/followers.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="col-md-6">
    <div class="card add-tweet-box">
        <div class="card-title">
            <h6 class="h5"><i class="fas fa-frog"></i> Followers</h6>
        </div>
        <div class="card-body">

            {% if obj.followed_by.all %}
            {% for profile in obj.followed_by.all %}

            <div class="followers">
                <a href="{{profile.get_absolute_url}}">
                    <div class='user-tweet-avatar'>
                        <img src='{{profile.avatar.url}}' />
                    </div>
                    <p class="lead">
                        {{profile.user.username}}
                    </p>
                </a>
            </div>
            {% endfor %}
            {% else %}

            <p class="lead">{{user.username|capfirst}} have no followers</p>
            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

templates/accounts/following.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="col-md-6">
    <div class="card add-tweet-box">
        <div class="card-title">
            <h6 class="h5"><i class="fas fa-fish"></i> You Follow</h6>
        </div>
        <div class="card-body">
            {% if obj.profile.get_following %}
            {% for user_ in obj.profile.get_following%}

            <div class="followers">
                <a href="{{user_.profile.get_absolute_url}}">
                    <div class='user-tweet-avatar'>
                        {% if user_.profile.avatar  %}
                        <img src='
                        {{user_.profile.avatar.url}}' />
                        {% else %}
                        <img src="
                        {% static 'images/blank-profile.png' %}" />
                        {% endif %}
                    </div>
                    <span class="lead">
                        {{user_.username}}

                    </span>
                </a>

                {% if request.user.is_authenticated and request.user == object %}
                <a href="{% url 'accounts:follow_manage' user_slug=user_.slug %}" class=" follow-btn btn btn-success">
                    Unfollow
                </a>

                {% endif %}

            </div>
            {% endfor %}

            {% else %}
            <p class="lead">{{user.username|capfirst}} did not follow any user yet</p>
            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

templates/accounts/login.html
{% extends 'layout.html' %}
{% block nav %}
{% include 'snippets/navbar.html' %}
{% endblock %}
{% block title %}Login{% endblock %}

{% block auth %}
{% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <div class='row'>
    {% if messages %}
    <div class=" col-lg-8 offset-lg-2 alert alert-success messages text-center">
      {% for message in messages %}
      <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>

        {{ message }}
      </span>
      {% endfor %}
    </div>
    {% endif %}
    <div class='col-lg-8 offset-lg-2'>
      <h2 class=' text-center display-4 myh2 login-heading'> Login
        <hr>
      </h2>

      <form method="post" class="login-form">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Login">
      </form>
      <br>

    </div>
  </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="col-md-6 card">

  <div class="card-title">
    <h6 class="h5">
      <i class="fas fa-user-circle"></i>&nbsp;
      <span>{{user.username|capfirst}}</span> Profile

    </h6>
  </div>

  <div class="user-profile">
    <div class="profile-imgs">
      <div class="profile-cover-img" style="
              
                background: url(
                  {% if object.profile.cover %}
                   {{object.profile.cover.url}});
                  {% else %} 
                   {% static 'images/default-cover.jpg' %}) center center;
                  {% endif %}
                background-size: cover;
              ">

        <div class="profile-img rounded-circle">
          <img src="{% if object.profile.avatar %}
                    {{object.profile.avatar.url}}
                    {% else %}
                    {% static 'images/blank-profile.png' %}
                    {% endif %}
                  ">
        </div>

        <div class="profile-user-name">
          <h3>{{object.username|capfirst}}</h3>
          {% if request.user == object %}
          <a href="{% url 'accounts:profile_update' pk=object.pk %}">Edit</a>
          {% endif %}
        </div>

      </div>
    </div>


    <div class="row">
      {% if not me and request.user.is_authenticated %}
      <div class="col-md-12 text-center">
        <a id='{{object.slug}}' href="{% url 'accounts:follow' user_slug=object.slug %}" class=" follow-btn btn">
          {% if is_followed %}
          Unfollow
          {% else %}
          follow
          {% endif %}
        </a>
      </div>
      {% endif %}
      <div class="col-md-6 text-center">

        <a href="{% url 'accounts:following' user_slug=object.slug %}" class="lead following-num">
          <i class="fa fa-user"></i> Following
          {{object.profile.get_following.count}}
        </a>
      </div>

      <div class="col-md-6 text-center">

        <a href="{% url 'accounts:followers' user_slug=object.slug %}" class="lead followers-num">
          <i class="fa fa-users"></i>
          Followers
          <span> {{object.followed_by.all.count}}</span>
        </a>


      </div>

      {% if object.profile.country %}
      <div class="col-md-4 offset-md-1 profile-info">
        <span>Country</span> {{object.profile.country.name}} <img src={{object.profile.country.flag}} />
      </div>
      {% endif %}

      {% if object.profile.birthday %}
      <div class="col-md-4 offset-md-1 profile-info">
        <span>Birthday</span> {{object.profile.birthday}}
      </div>
      {% endif %}

      {% if object.profile.description  %}
      <div class="col-md-8 offset-md-2 user-des text-center">
        <h6>description</h6>
        <p class="profile-des">{{object.profile.description}}</p>
      </div>
      {% endif %}

    </div>
    <div class="text-center">

      <h5 class="user-tweets ">User Tweets</h5>
    </div>
    <section id='tweets' data-url='/api/{{object.slug}}/tweets/'>

    </section>

    <section>
      <div class="row">
        <div class="col-md-12 text-center">
          <button id='load-more-btn' class="btn btn-link">
            Load more
          </button>
        </div>
      </div>
    </section>
  </div>


</div>
{% endblock %}


{% block script %}
<script>
  $(function () {
    loadTweetsContainer('tweets')
  })
</script>
{% endblock %}




<!-- {% with profiles=user.followed_by.all%}
        {% if profiles %}
        {% for profile in profiles  %}
        {{profile.user.username}}
        {% endfor %}
        {% else %}
        no one follow you
        {% endif %}
        {% endwith %} -->

<!-- {% with users=user.profile.following.all%}
        {% if users %}
        {% for user in users  %}
        {{user}}
        {% endfor %}
        {% else %}
        You don't follow anyone
        {% endif %}
        {% endwith %} -->

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="col-md-6">
    <div class="card add-tweet-box">
        <div class="card-title">
            <h6 class="h5">
                <i class="fas fa-user-edit "></i> {{object.user.username|capfirst}}</h6>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success">
                    Save
                </button>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/accounts/register.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}
{% block nav %}
{% include 'snippets/navbar.html' %}
{% endblock %}

{% block auth %}
{% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <div class='row'>
    <div class='col-lg-8 offset-lg-2'>
      <h2 class=' text-center display-4 myh2 register-heading'> Register
        <hr>
      </h2>
      <form method="post" class="register-form">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Register">
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/user_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

  <div class='container'>
    <div class='row '>
      <div class='col-lg-12 p-4'>

          <h1 class="text-center mt-5 display-4">
            Delete User <hr>
          </h1>
          <p class='text-center lead'> Are you sure you want to delete
            {% if request.user.is_admin and object.username != request.user.username %}
              {{object.username|capfirst}} ? </p>
            {% else %}
              Your account
            {% endif %}
          <form class='text-center' method='post'>
            {% csrf_token %}
            <button class='btn btn-dark mb-5'>Delete</button>
          </form>
      </div>
    </div>
    </div>

{% endblock %}