accounts/urls.py
from django.urls import path


from .views import (UserLoginView, UserRegistrerView, UserProfileUpdateView,
                    UserLogoutView, UserProfileView, UserFollow, ThemeChange,
                    FollowManager, FollowingView, FollowersView)
from tweets.api.views import ProfileLikeToggleApiView


app_name = 'accounts'
urlpatterns = [

    path('theme/', ThemeChange.as_view(), name='theme'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrerView.as_view(), name='register'),
    path('<slug:user_slug>/follow/', UserFollow.as_view(), name='follow'),
    path('<slug:user_slug>/follow_manage/',
         FollowManager.as_view(), name='follow_manage'),
    path('<slug:user_slug>/', UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('<slug:user_slug>/followers/',
         FollowersView.as_view(), name='followers'),
    path('<slug:user_slug>/following/',
         FollowingView.as_view(), name='following'),
    path('<slug:slug>/api/tweets/<int:pk>/like/',
         ProfileLikeToggleApiView.as_view(), name='user-like'),
]

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import (TweetListView,
                    TweetDetailView,
                    TweetCreateView,
                    TweetEditView,
                    TweetDeleteView,
                    RetweetView)

app_name = 'tweets'
urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),
    path('edit/<int:pk>/', TweetEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', TweetDeleteView.as_view(), name='delete'),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm
from .models import User, UserProfile

import re


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Email ", widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=("Password "),
        strip=False,
        widget=forms.PasswordInput,
    )
    remember_me = forms.BooleanField(required=False, label='Remember me')


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_password2(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]


class UserProfileForm(forms.ModelForm):
    birthday = forms.DateField(required=False, input_formats=['%Y-%m-%d'])

    class Meta:
        model = UserProfile
        exclude = ['user', 'following', 'color']

    def clean_birthday(self):
        birthday = self.cleaned_data.get('birthday')
        return birthday


class UserProfileColorForm(forms.ModelForm):
    color = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = UserProfile
        fields = ['color']

    def clean_color(self):
        regex = r'^\s*#[\w\d]{6}\s*$'
        color = self.cleaned_data.get('color')
        m = re.match(regex, color)
        if not m:
            raise forms.ValidationError('Please type a valid color code ')
        return m.string

templates/snippets/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet"
	integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">


<link rel="stylesheet" type="text/css"
	href="	  https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css">


<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

<link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">

templates/snippets/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>

<!-- Compiled and minified JavaScript -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js">
</script>

<script src="{% static 'js/csrf.ajax.js' %}">
</script>

<script>
  $(function () {
    $("#id_birthday").datepicker({
      format: 'yyyy-mm-dd',
    });
  });
</script>



<script src="{% static 'js/custom.js' %}">
</script>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light ">
  <a class="navbar-brand" href="#">
  
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if request.get_full_path == "/account/login/" %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        {% endif %}
      


    </ul>
   <!--  <ul class="navbar-nav ">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}"> Logout</a>
      </li>
  
    </ul> -->


  </div>
</nav>