tweets/api/urls.py
from .views import (TweetListAPIView,
                    TweetAddAPIView,
                    RetweetApiView,
                    LikeToggleApiView,
                    TweetDetailAPIView,
                    TweetDeleteAPIView)
from django.urls import path
app_name = 'api'
urlpatterns = [
    path('', TweetListAPIView.as_view(), name='list'),
    path('add/', TweetAddAPIView.as_view(), name='add'),
    path('<int:pk>/like/', LikeToggleApiView.as_view(), name='like'),
    path('<int:pk>/delete/', TweetDeleteAPIView.as_view(), name='delete'),

    path('<int:pk>/retweet/', RetweetApiView.as_view(), name='retweet'),
    path('<int:pk>/', TweetDetailAPIView.as_view(), name='detail'),
]

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import (TweetListView,
                    TweetDetailView,
                    TweetCreateView,
                    TweetEditView,
                    TweetDeleteView,
                    RetweetView)

app_name = 'tweets'
urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),
    path('edit/<int:pk>/', TweetEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', TweetDeleteView.as_view(), name='delete'),
]

tweets/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

from django_resized import ResizedImageField

from .utils import get_tweet_image_name
from .validators import validate_content


class TweetManager(models.Manager):
    def retweet(self, user, parent_obj):
        if parent_obj.parent:
            parent_obj = parent_obj.parent
        qs = Tweet.objects.filter(user=user, parent=parent_obj,
                                  timestamp__date=timezone.now(),
                                  reply=False)
        if qs.exists():
            return None
        obj = self.model(user=user,
                         parent=parent_obj,
                         content=parent_obj.content)
        obj.save()
        return obj

    def like_toggle(self, user, tweet):
        if user in tweet.liked.all():
            is_like = False
            tweet.liked.remove(user)
        else:
            is_like = True
            tweet.liked.add(user)
        return is_like


User = settings.AUTH_USER_MODEL


class Tweet(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    content = models.CharField(max_length=255, validators=[validate_content])
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                               null=True, blank=True)
    liked = models.ManyToManyField(User, related_name='liked',
                                   blank=True)
    image = ResizedImageField(size=[500, 300],
                              upload_to=get_tweet_image_name, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    reply = models.BooleanField(verbose_name='Is a reply?', default=False)

    objects = TweetManager()

    def __str__(self):
        if self.parent and self.reply:
            return '(reply via ' + self.user.username + ')'
        elif self.parent:
            return ' (retweeted via ' + self.user.username + ')'
        return self.user.username

    def get_absolute_url(self):
        return reverse('tweets:detail', kwargs={'pk': self.pk})

    def get_parent(self):
        parent = self
        if self.parent:
            parent = self.parent
        return parent

    def get_children(self):
        parent = self.get_parent()
        qs1 = Tweet.objects.filter(parent=parent)
        qs2 = Tweet.objects.filter(pk=parent.pk)
        return (qs1 | qs2)

tweets/forms.py
from django import forms

from .models import Tweet
from django.core import validators


class AddTweetForm(forms.ModelForm):
    content = forms.CharField(label='',
                              widget=forms.Textarea(attrs={'placeholder': 'What\'s Happening',
                                                           'class': 'form-control'}),
                              validators=[validators.MaxLengthValidator(255)]

                              )
    image = forms.ImageField(label='', required=False)

    class Meta:
        model = Tweet
        fields = ['content', 'image']

tweets/api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db.models import Q

from .serializers import TweetModelSerializer
from tweets.models import Tweet
from .pagination import StandardTweetsPagination
from accounts.models import UserProfile


class LikeToggleApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk, format=None):
        user = request.user
        tweet = get_object_or_404(Tweet, pk=pk)
        liked_tweet = Tweet.objects.like_toggle(user, tweet)
        liked_num = tweet.liked.all().count()
        return Response({'liked': liked_tweet,
                         'likedNum': liked_num})


class ProfileLikeToggleApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk, slug, format=None):
        user = request.user
        tweet = get_object_or_404(Tweet, pk=pk)
        liked_tweet = Tweet.objects.like_toggle(user, tweet)
        # data = TweetModelSerializer(liked_tweet).data
        return Response({'liked': liked_tweet})


class RetweetApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk, format=None):
        user = request.user
        msg = 'Not allowed'
        tweet = get_object_or_404(Tweet, pk=pk, user=user)
        retweet = Tweet.objects.retweet(user, tweet)
        if retweet is not None:
            data = TweetModelSerializer(
                retweet, context={'request': request}).data
            return Response(data)
            msg = 'you can\'t retweet the same in 1 day '
        return Response({'message': msg, 'id': tweet.id}, status=400)


class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer
    pagination_class = StandardTweetsPagination

    def get_queryset(self):
        q = self.request.GET.get('q')
        user = self.request.user
        filters = Q(content__iexact='fhgt$$dge#wr$$*HGF')
        slug = self.kwargs.get('user_slug')
        if user.is_authenticated:
            users = user.profile.get_following()
            filters = Q(user__in=users) | Q(user=user)
        else:
            q = ' '

        if slug:
            filters = Q(user__slug=slug)

        if q is not None and q != '':
            filters = Q(content__icontains=q) | Q(user__username__icontains=q)

        qs = Tweet.objects.filter(filters).distinct().order_by('-timestamp')
        return qs

    def get_serializer_context(self, *args, **kwargs):
        context = super().get_serializer_context(*args, **kwargs)
        context['request'] = self.request
        return context


class TweetAddAPIView(generics.CreateAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class TweetDeleteAPIView(generics.DestroyAPIView):
    queryset = Tweet.objects.all()
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_object(self):
        obj = super().get_object()
        user = self.request.user
        if obj.user != user:
            raise Http404
        return obj


class TweetDetailAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.AllowAny]
    pagination_class = StandardTweetsPagination

    def get_queryset(self, *args, **kwargs):
        tweet_id = self.kwargs.get('pk')
        qs = Tweet.objects.filter(pk=tweet_id)
        if qs.exists() and qs.count() == 1:
            parent = qs.first()
            qs1 = parent.get_children()
            qs = (qs | qs1).distinct().extra(
                select={'parent_is_null': 'parent_id IS NULL'})
        return qs.order_by('-parent_is_null', 'timestamp')

tweets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views import View

from .mixins import (MustLoggedInMixin, UserOwnerMixin)
from .forms import AddTweetForm
from .models import Tweet


class TweetListView(generic.ListView):
    context_object_name = 'tweets'
    template_name = 'main/home.html'

    def get_queryset(self):
        q = self.request.GET.get('q')
        if q is not None:
            filters = Q(content__icontains=q) | Q(user__username__icontains=q)
            qs = Tweet.objects.filter(filters)
            return qs
        qs = Tweet.objects.all()
        return qs

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)
        context['create_form'] = AddTweetForm()

        return context


class TweetDetailView(generic.DetailView):
    model = Tweet
    fileds = '__all__'
    context_object_name = 'tweet'
    template_name = 'tweets/tweet_details.html'


class TweetCreateView(MustLoggedInMixin, generic.CreateView):
    form_class = AddTweetForm
    template_name = 'tweets/add_tweet.html'


class TweetEditView(LoginRequiredMixin, UserOwnerMixin, generic.UpdateView):
    form_class = AddTweetForm
    queryset = Tweet.objects.all()
    success_url = reverse_lazy('home')
    template_name = 'tweets/tweet_edit.html'


class TweetDeleteView(LoginRequiredMixin, UserOwnerMixin, generic.DeleteView):
    model = Tweet
    success_url = reverse_lazy('home')
    template_name = 'tweets/tweet_delete_confirm.html'


class RetweetView(View):
    def get(self, request, pk, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=pk)
        user = request.user
        if user.is_authenticated:
            new_tweet = Tweet.objects.retweet(user, tweet)
            return redirect('/')
        else:
            return redirect('/')

templates/tweets/add_tweet.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">

		<div class="col-md-8 offset-md-2">
			{% include 'tweets/snippets/form.html' with status='success' mybtn='Tweet' %}
		</div>
	</div>
{% endblock %}

templates/tweets/tweet_delete_confirm.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-sm-12">
			<form method="post">
				{% csrf_token %}
				<p class="lead">Are you sure you want to delete your tweet !!</p>
				<button class="btn btn-danger">Delete</button>
				
			</form>
		</div>
	</div>
{% endblock %}

templates/tweets/tweet_details.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-6">
	<div class="card add-tweet-box">
		<div class="card-title">
			<h6 class="h5"><a style="text-decoration: none;" href="{% url 'home' %}">
					<i class="fa fa-home"></i> Go Home</h6>
			</a>
		</div>
		<div class="card-body">
			<section id='tweet'>
			</section>
			<section>
				<!-- <div class="row">
					<div class="col-md-12 text-center">
						<button id='load-more-btn' class="btn btn-link">
							Load more
						</button>
					</div>
				</div> -->
			</section>
		</div>
	</div>

</div>
{% endblock %}

{% block  script %}
<script>
	$(function () {
		loadTweetsContainer('tweet', {{ tweet.id }})
	})
</script>
{% endblock %}

templates/tweets/tweet_edit.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-sm-12">
			{% include 'tweets/snippets/form.html' with status='info' mybtn='Update' %}
		</div>
	</div>
{% endblock %}

templates/tweets/tweet_list.html
{% extends 'base.html' %}

{% block content %}
	<div>
	<div class="row">
		<div class="col-md-3">
				<div class="card" style="width: 15rem;">
  					<div class="card-body text-center">
  						<div class="row">
  							<div class="col-12">
  								<a  href='#' class="btn btn-link"><i class="fas fa-home fa-lg"></i> Home</a>		
  							</div>
  							<div class="col-12">
  								<a href='#' class="btn btn-link"><i class="fas fa-user-circle fa-lg"></i> Profile</a>		
  							</div>
  							<div class="col-12">
  								<a  href='#' class="btn btn-link">
  									<i class="fas fa-plus fa-lg"></i> Tweet</a>		
  							</div>
  						</div>
  						
  						
  					</div>
				</div>		
		</div>

		<div class="col-md-6">
				<div class="card">
				  	<div class="card-body">
				  		{% if tweets %}
							{% for tweet in tweets %}
						  		<section class="tweet"> 
						  			<div class="tweet-header">
						 	 			<span class=" btn-link">{{tweet.user.username|capfirst}}</span>
						 	 			<span>. {{tweet.timestamp|timesince}}</span>
						 	 		</div>

						 	 		<div class="tweet-body">
						 	 			<p class="lead">{{tweet.content}}</p>

						 	 		</div>
						 	 		<hr />
						 	 	</section>
						 	{% endfor %}
						{% endif %}
				 	 </div>
				</div>			
		</div>
		<div class="col-md-3">
				<div class="card" >
  					<div class="card-body">
  						 <form action="{% url 'tweets:list' %}" class="form-inline my-2 my-lg-0">
					      <input class="form-control mr-sm-2" name='q'
					             type="search" placeholder="Search" aria-label="Search">
					      <button class="btn btn-outline-success my-2 my-sm-0" 
					              type="submit">
					            Search
					      </button>
					    </form>
  					</div>
				</div>		
		</div>
	</div>

	<!-- <div class="row">
		<div class="col-sm-12">
			<h2>Tweets <hr></h2>
		</div>
		{% if tweets %}
			{% for tweet in tweets %}
				<div class="col-sm-12">
					<p class="lead">{{tweet.content}}
						<br>
						<a href="{% url 'tweets:detail' pk=tweet.pk%}">View</a>
						<span class="span" >{{tweet.timestamp|timesince}}</span>
					</p>

				</div>
			{% endfor %}
		{% else %}
		{% if request.GET.q %}
			<p>No Tweets Found</p>
		{% else %}
			<p>There are no tweets</p>
		{% endif %}
			
		{% endif %}
	</div> -->
{% endblock %}