accounts/urls.py
from django.urls import path


from .views import (UserLoginView, UserRegistrerView, UserProfileUpdateView,
                    UserLogoutView, UserProfileView, UserFollow, ThemeChange,
                    FollowManager, FollowingView, FollowersView)
from tweets.api.views import ProfileLikeToggleApiView


app_name = 'accounts'
urlpatterns = [

    path('theme/', ThemeChange.as_view(), name='theme'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrerView.as_view(), name='register'),
    path('<slug:user_slug>/follow/', UserFollow.as_view(), name='follow'),
    path('<slug:user_slug>/follow_manage/',
         FollowManager.as_view(), name='follow_manage'),
    path('<slug:user_slug>/', UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('<slug:user_slug>/followers/',
         FollowersView.as_view(), name='followers'),
    path('<slug:user_slug>/following/',
         FollowingView.as_view(), name='following'),
    path('<slug:slug>/api/tweets/<int:pk>/like/',
         ProfileLikeToggleApiView.as_view(), name='user-like'),
]

tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import (TweetListView,
                    TweetDetailView,
                    TweetCreateView,
                    TweetEditView,
                    TweetDeleteView,
                    RetweetView)

app_name = 'tweets'
urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='retweet'),
    path('edit/<int:pk>/', TweetEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', TweetDeleteView.as_view(), name='delete'),
]

templates/base.html
{% extends 'layout.html' %}
{% block base %}
{% load recommended %}


<div class="row">
  <div class="col-md-3">
    <div class="card home-raw-box">
      <div class="card-body text-left">
        <div class="row">
          <div class="card-title">
            <span><i class="fas fa-dragon"></i></span>
            <h4>Tweet Me</h4>
          </div>

          <div class="col-sm-12">
            <span><i class="fa fa-home"></i></span>
            <a href="{% url 'home' %}">Home</a>
          </div>
          {% if request.user.is_authenticated %}
          <div class="col-sm-12">
            <span><i class="fa fa-user-circle"></i></span>

            <a href="{% url 'accounts:profile' user_slug=request.user.slug %}">Profile</a>
          </div>
          <div class="col-sm-12">
            <span><i class="fas fa-sign-out-alt"></i></span>

            <a href="{% url 'accounts:logout' %}"> Logout</a>

          </div>
          {% else %}
          <div class="col-sm-12">
            <span><i class="fas fa-sign-in-alt"></i></span>
            <a href="{% url 'accounts:login' %}"> Login</a>

          </div>
          <div class="col-sm-12">
            <span> <i class="fas fa-user-plus"></i></span>
            <a href="{% url 'accounts:register' %}">Register</a>
          </div>


          {% endif %}

        </div>

        {% include 'tweets/snippets/reply_modal.html' %}

      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <br />
        <form method="post" action="{% url 'accounts:theme' %}" id='theme-form'>
          <label class="color-picker-label text-center">Theme Color</label>
          {% csrf_token %}
          {{ color_form }}
          <br />
          <input id='current-path' type="hidden" name='current_path' value="{{request.path}}" />
          <input id='current-color' type="color" name='current_color' value="{{color}}" />
          <button type="submit" class="color-picker-btn">
            Change
          </button>
        </form>
      </div>
    </div>

  </div>

  {% block content %}{% endblock %}
  {% if not request.GET.q %}
  <div class="col-md-3">
    <div class="card search-box">
      <div class="card-body">
        {% include 'main/snippets/search_form.html'  %}
        {% recommended_users request.user %}
      </div>
    </div>

  </div>
  {% else %}
  {% include 'main/snippets/custom_search.html'  %}
  {% endif %}
</div>



{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>

<head>

	<title>{% block title %}{% endblock %}</title>
	{% include 'snippets/css.html' %}

</head>


<body>

	{% block nav %}

	{% endblock %}

	{% block base %}{% endblock %}
	{% block auth %}{% endblock %}
	{% include 'snippets/js.html' %}
	{% block script %}{% endblock %}
</body>

</html>